services:
  - type: web
    name: solvexpert
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Solvexpert.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Solvexpert.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
